-- 校园闲置物品交易信息管理系统：Supabase/PostgreSQL 最终 8 表版
-- 使用方式：在 Supabase SQL Editor 中整段运行。
-- 该脚本会清空旧表并重建数据结构，请确认数据库中没有需要保留的数据。

drop table if exists ratings cascade;
drop table if exists disputes cascade;
drop table if exists operation_logs cascade;
drop table if exists orders cascade;
drop table if exists payment cascade;
drop table if exists goods_image cascade;
drop table if exists goods cascade;
drop table if exists products cascade;
drop table if exists profiles cascade;
drop table if exists dispute cascade;
drop table if exists category cascade;
drop table if exists admin cascade;
drop table if exists "user" cascade;

create table "user" (
  user_id bigint generated by default as identity primary key,
  username varchar(30) not null unique,
  password varchar(100) not null,
  nickname varchar(30),
  real_name varchar(20),
  student_no varchar(20),
  phone varchar(20),
  wechat varchar(50),
  email varchar(50),
  avatar varchar(255),
  status smallint not null default 1 check (status in (0, 1)),
  create_time timestamptz not null default now()
);

create table admin (
  admin_id bigint generated by default as identity primary key,
  username varchar(30) not null unique,
  password varchar(100) not null,
  name varchar(20),
  phone varchar(20),
  role varchar(20),
  create_time timestamptz not null default now()
);

create table category (
  category_id bigint generated by default as identity primary key,
  category_name varchar(30) not null,
  sort integer default 0,
  status smallint not null default 1 check (status in (0, 1))
);

create table goods (
  goods_id bigint generated by default as identity primary key,
  seller_id bigint not null references "user"(user_id),
  category_id bigint not null references category(category_id),
  goods_name varchar(100) not null,
  description text,
  price numeric(10, 2) not null,
  original_price numeric(10, 2),
  degree varchar(20),
  location varchar(100),
  status smallint not null default 0 check (status in (0, 1, 2, 3, 4, 5)),
  view_count integer default 0,
  publish_time timestamptz not null default now(),
  update_time timestamptz
);

create table goods_image (
  image_id bigint generated by default as identity primary key,
  goods_id bigint not null references goods(goods_id) on delete cascade,
  image_url varchar(255) not null,
  sort integer default 0,
  is_cover smallint not null default 0 check (is_cover in (0, 1)),
  upload_time timestamptz not null default now()
);

create table payment (
  payment_id bigint generated by default as identity primary key,
  payment_no varchar(50) not null unique,
  order_no varchar(50),
  buyer_id bigint not null references "user"(user_id),
  goods_id bigint not null references goods(goods_id),
  pay_amount numeric(10, 2) not null,
  pay_method varchar(20) not null,
  pay_status smallint not null default 0 check (pay_status in (0, 1, 2, 3)),
  pay_time timestamptz
);

create table orders (
  order_id bigint generated by default as identity primary key,
  order_no varchar(50) not null unique,
  goods_id bigint not null unique references goods(goods_id),
  buyer_id bigint not null references "user"(user_id),
  seller_id bigint not null references "user"(user_id),
  payment_id bigint not null unique references payment(payment_id),
  amount numeric(10, 2) not null,
  status smallint not null default 1 check (status in (1, 2, 3, 4, 5, 6)),
  place_location varchar(100),
  buyer_phone varchar(20),
  buyer_wechat varchar(50),
  seller_phone varchar(20),
  seller_wechat varchar(50),
  create_time timestamptz not null default now(),
  finish_time timestamptz
);

create table dispute (
  dispute_id bigint generated by default as identity primary key,
  order_id bigint not null references orders(order_id) on delete cascade,
  user_id bigint not null references "user"(user_id),
  reason text not null,
  evidence varchar(255),
  status smallint not null default 0 check (status in (0, 1, 2)),
  admin_id bigint references admin(admin_id),
  result text,
  create_time timestamptz not null default now(),
  handle_time timestamptz
);

alter table "user" enable row level security;
alter table admin enable row level security;
alter table category enable row level security;
alter table goods enable row level security;
alter table goods_image enable row level security;
alter table payment enable row level security;
alter table orders enable row level security;
alter table dispute enable row level security;

create policy "user readable" on "user" for select using (true);
create policy "user insertable" on "user" for insert with check (true);
create policy "user updatable" on "user" for update using (true);

create policy "admin readable" on admin for select using (true);
create policy "admin insertable" on admin for insert with check (true);
create policy "admin updatable" on admin for update using (true);

create policy "category readable" on category for select using (true);
create policy "category insertable" on category for insert with check (true);
create policy "category updatable" on category for update using (true);

create policy "goods readable" on goods for select using (true);
create policy "goods insertable" on goods for insert with check (true);
create policy "goods updatable" on goods for update using (true);

create policy "goods image readable" on goods_image for select using (true);
create policy "goods image insertable" on goods_image for insert with check (true);
create policy "goods image updatable" on goods_image for update using (true);

create policy "payment readable" on payment for select using (true);
create policy "payment insertable" on payment for insert with check (true);
create policy "payment updatable" on payment for update using (true);

create policy "orders readable" on orders for select using (true);
create policy "orders insertable" on orders for insert with check (true);
create policy "orders updatable" on orders for update using (true);

create policy "dispute readable" on dispute for select using (true);
create policy "dispute insertable" on dispute for insert with check (true);
create policy "dispute updatable" on dispute for update using (true);

insert into category (category_id, category_name, sort, status) values
  (1, '教材资料', 1, 1),
  (2, '数码电子', 2, 1),
  (3, '生活用品', 3, 1),
  (4, '服饰鞋包', 4, 1),
  (5, '运动户外', 5, 1),
  (6, '宿舍家具', 6, 1),
  (7, '文具工具', 7, 1),
  (8, '其他闲置', 8, 1);

insert into admin (admin_id, username, password, name, phone, role) values
  (1, 'admin@example.com', 'admin123', '管理员', '13800000000', 'super');

insert into "user" (user_id, username, password, nickname, real_name, phone, wechat, email, status) values
  (1, 'lin@example.com', 'demo', '林同学', '林同学', '13600005531', 'lin-campus', 'lin@example.com', 1),
  (2, 'zhou@example.com', 'demo', '周同学', '周同学', '13900006642', 'zhou-campus', 'zhou@example.com', 1);

insert into goods (goods_id, seller_id, category_id, goods_name, description, price, original_price, degree, location, status) values
  (1, 1, 1, '高等数学教材', '公共课教材，适合期末复习。', 28.00, 45.00, '八成新', '东校区图书馆自取柜 A-12', 1),
  (2, 1, 2, '机械键盘', '按键正常，适合宿舍学习。', 99.00, 199.00, '九成新', '北校区二号宿舍大厅', 1);

select setval(pg_get_serial_sequence('"user"', 'user_id'), 100, true);
select setval(pg_get_serial_sequence('admin', 'admin_id'), 100, true);
select setval(pg_get_serial_sequence('category', 'category_id'), 100, true);
select setval(pg_get_serial_sequence('goods', 'goods_id'), 100, true);

notify pgrst, 'reload schema';
