-- 修复登录时报错：Could not find the table 'public.user' in the schema cache
-- 使用方式：在 Supabase SQL Editor 中整段运行。

create table if not exists "user" (
  user_id bigint generated by default as identity primary key,
  username varchar(30) not null unique,
  password varchar(100) not null,
  nickname varchar(30),
  real_name varchar(20),
  student_no varchar(20),
  phone varchar(20),
  wechat varchar(50),
  email varchar(50),
  avatar varchar(255),
  status smallint not null default 1 check (status in (0, 1)),
  create_time timestamptz not null default now()
);

alter table "user" enable row level security;

drop policy if exists "user readable" on "user";
drop policy if exists "user insertable" on "user";
drop policy if exists "user updatable" on "user";

create policy "user readable" on "user" for select using (true);
create policy "user insertable" on "user" for insert with check (true);
create policy "user updatable" on "user" for update using (true);

insert into "user" (user_id, username, password, nickname, real_name, phone, wechat, email, status)
values
  (1, 'lin@example.com', 'demo', '林同学', '林同学', '13600005531', 'lin-campus', 'lin@example.com', 1),
  (2, 'zhou@example.com', 'demo', '周同学', '周同学', '13900006642', 'zhou-campus', 'zhou@example.com', 1)
on conflict (username) do nothing;

select setval(pg_get_serial_sequence('"user"', 'user_id'), 100, true);

notify pgrst, 'reload schema';
